# Generated by Django 4.2.7 on 2026-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('hr', 'HR Manager'), ('employee', 'Regular Employee')], default='employee', max_length=20),
        ),
    ]
