# Generated by Django 4.2.7 on 2026-04-11 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('custody_type', models.CharField(choices=[('office_equipment', 'Office Equipment Custody'), ('vehicle', 'Vehicle Custody'), ('it_equipment', 'IT / Technical Equipment Custody'), ('cash', 'Cash Custody'), ('documents', 'Documents / Records Custody'), ('tools', 'Tools / Equipment Custody'), ('other', 'Special / Other Custody')], max_length=50)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Under Maintenance'), ('damaged', 'Damaged'), ('disposed', 'Disposed')], default='available', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('asset_photo', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='assets/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.asset')),
                ('from_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_out', to=settings.AUTH_USER_MODEL)),
                ('to_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_transferred_in', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_handled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assetcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
