# Generated by Django 4.2.7 on 2026-04-11 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asset_assetcategory_assettransfer_asset_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettransfer',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='from_employee',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='to_employee',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='transferred_by',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='purchase_date',
            new_name='expected_return_date',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='return_date',
            new_name='returned_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_photo',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_tag',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_cost',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='receipt_photo',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='warranty_expiry',
        ),
        migrations.AddField(
            model_name='asset',
            name='condition_on_handover',
            field=models.TextField(blank=True, help_text='Condition when handed over'),
        ),
        migrations.AddField(
            model_name='asset',
            name='condition_on_return',
            field=models.TextField(blank=True, help_text='Condition when returned'),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AssetCategory',
        ),
        migrations.DeleteModel(
            name='AssetTransfer',
        ),
    ]
