# Generated by Django 4.2.30 on 2026-04-11 13:38

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_assettransfer_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='SA', max_length=2),
        ),
    ]
