# Generated by Django 4.2.30 on 2026-04-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='zktecodevice',
            name='connection_status',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='zktecodevice',
            name='device_firmware',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='zktecodevice',
            name='device_mac',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='zktecodevice',
            name='device_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='zktecodevice',
            name='device_platform',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='zktecodevice',
            name='device_serial_no',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
