# Generated by Django 4.2.30 on 2026-04-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_zktecodevice_connection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zktecodevice',
            name='password',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ZKAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(blank=True, max_length=200)),
                ('punch_time', models.DateTimeField()),
                ('punch_type', models.CharField(blank=True, max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.zktecodevice')),
            ],
            options={
                'ordering': ['-punch_time'],
            },
        ),
    ]
