# Generated by Django 4.2.30 on 2026-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_zktecodevice_password_zkattendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='zkteco_uid',
            field=models.CharField(blank=True, help_text='Numeric User ID assigned by the ZKTeco device (shown in device logs)', max_length=20, null=True),
        ),
    ]
