# Generated by Django 4.2.30 on 2026-04-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employee_zkteco_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('hr', 'HR'), ('manager', 'Manager'), ('branch_manager', 'Branch Manager'), ('officer', 'Officer'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
