# Generated by Django 4.2.30 on 2026-04-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_advancesalaryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='approval_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('branch_approved', 'Branch Manager Approved'), ('manager_approved', 'Manager Approved'), ('ceo_approved', 'CEO Approved'), ('hr_approved', 'HR Approved'), ('approved', 'Approved'), ('refused', 'Refused')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='refused_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='requester_role',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('officer', 'Officer'), ('branch_manager', 'Branch Manager'), ('manager', 'Manager'), ('hr', 'HR')], max_length=20),
        ),
    ]
