# Generated by Django 4.2.30 on 2026-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_timeoffrequest_approval_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancesalaryrequest',
            name='approval_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('hr_approved', 'HR Approved'), ('accountant_approved', 'Accountant Approved'), ('sub_accountant_approved', 'Sub Accountant Approved'), ('ceo_approved', 'CEO Approved'), ('bank_approved', 'Bank Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='advancesalaryrequest',
            name='requester_role',
            field=models.CharField(blank=True, choices=[('top_manager', 'Top Manager'), ('hr', 'HR'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='advance_role',
            field=models.CharField(blank=True, choices=[('top_manager', 'Top Manager'), ('accountant', 'Accountant'), ('sub_accountant', 'Sub Accountant'), ('bank_user', 'Bank User')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO 👑'), ('hr', 'HR ⭐ '), ('manager', 'Manager'), ('branch_manager', 'Branch Manager'), ('officer', 'Officer'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
