# Generated by Django 4.2.30 on 2026-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_advancesalaryrequest_approval_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='timeoff_documents/'),
        ),
    ]
