# Generated by Django 4.2.30 on 2026-04-15 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numbers allowed')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='iqama_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numbers allowed')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numbers allowed')]),
        ),
    ]
