# Generated by Django 4.2.30 on 2026-04-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_employee_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
