# Generated by Django 4.2.30 on 2026-04-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_employee_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
