# Generated by Django 4.2.30 on 2026-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_employee_emergency_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('christianity', 'Christianity'), ('judaism', 'Judaism'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('sikhism', 'Sikhism'), ('other', 'Other')], max_length=20),
        ),
    ]
