# Generated by Django 4.2.30 on 2026-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_employee_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('alrajhi', 'Al Rajhi Bank'), ('alinma', 'Alinma Bank'), ('riyad', 'Riyad Bank'), ('snb', 'Saudi National Bank (SNB)'), ('sabb', 'SABB (Saudi British Bank)'), ('albilad', 'Bank Albilad'), ('aljazira', 'Bank Aljazira'), ('arab_national', 'Arab National Bank'), ('gulf_international', 'Gulf International Bank'), ('saudi_investment', 'The Saudi Investment Bank'), ('emirates_nbd', 'Emirates NBD'), ('bank_muscat', 'Bank Muscat'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_relationship',
            field=models.CharField(blank=True, choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('christianity', 'Christianity'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('sikhism', 'Sikhism'), ('judaism', 'Judaism'), ('other', 'Other')], max_length=50),
        ),
    ]
